name = 'My Game'

modules = [
   './inventory',
   '@rpgjs/title-screen',
   './spritesheets',
   './character-select',
    './main',
    '@rpgjs/default-gui',
]

spritesheetDirectories = [
    'lpc/heads',
    'lpc/bodies',
    'lpc/accessories',
    'lpc/torso',
    'lpc/legs',
    'lpc/hair',
    'lpc/ears',
]

[start]
    map = 'simplemap'
    hitbox = [32, 32]

[titleScreen]
    mongodb = "$ENV:VITE_MONGODB_URL"

[characterSelect]
  actors = [
    'human',
    'elf',
    'vampire',
  ]

