name = 'My Game'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = './main/maps/simplemap'
    graphic = 'hero'
    hitbox = [16, 16]
